spring:
  config:
    import: optional:application-secret.yml

  datasource:
    url: jdbc:mysql://localhost:3306/billing_app
    username: root
    password: root

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_NAME}
    password: ${PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false

  main:
    banner-mode: off

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}

payment:
  upi-max-transaction-inr: 100000

server:
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.eclipse.angus.mail: DEBUG
    jakarta.mail: DEBUG
    com.intech.dukaantech: DEBUG