spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/billing_app}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}


  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}

razorpay:
  key-id: ${RAZORPAY_ID}
  key-secret: ${RAZORPAY_SECRET}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}

jwt:
  secret: ${JWT_SECRET}